from django.urls import path
from . import views

urlpatterns = [
    path(
        "settings/programmes-orientation/",
        views.programme_orientation_list,
        name="programme_orientation_list"
    ),
    path(
        "settings/programmes-orientation/ajouter/",
        views.programme_orientation_create,
        name="programme_orientation_create"
    ),
    path(
        "settings/programmes-orientation/<int:pk>/modifier/",
        views.programme_orientation_update,
        name="programme_orientation_update"
    ),
    path(
        "settings/programmes-orientation/<int:pk>/supprimer/",
        views.programme_orientation_delete,
        name="programme_orientation_delete"
    ),
     path(
        "orientation-scolaire/",
        views.orientation_scolaire_list,
        name="orientation_scolaire_list"
    ),
    path(
        "orientation-scolaire/ajouter/",
        views.orientation_scolaire_create,
        name="orientation_scolaire_create"
    ),
    path(
        "orientation-scolaire/<int:pk>/modifier/",
        views.orientation_scolaire_update,
        name="orientation_scolaire_update"
    ),
    path(
        "orientation-scolaire/<int:pk>/supprimer/",
        views.orientation_scolaire_delete,
        name="orientation_scolaire_delete"
    ),
     path(
        "orientation/fiche-voeux/",
        views.fiche_voeux_list,
        name="fiche_voeux_list"
    ),

    path(
        "orientation/ajax/niveaux-orientation/",
        views.ajax_niveaux_orientation,
        name="ajax_niveaux_orientation"
    ),

    path(
        "orientation/ajax/classes-par-niveau/",
        views.ajax_classes_par_niveau,
        name="ajax_classes_par_niveau"
    ),
    path(
        "orientation/saisie-voeux/",
        views.saisie_voeux_orientation,
        name="saisie_voeux_orientation"
    ),
    path(
        "orientation/ajax/niveaux-orientation/",
        views.ajax_niveaux_orientation,
        name="ajax_niveaux_orientation"
    ),
    path(
        "orientation/ajax/classes-par-niveau/",
        views.ajax_classes_par_niveau,
        name="ajax_classes_par_niveau"
    ),
]
urlpatterns += [
    path(
        "orientation/afficher-voeux/",
        views.voeux_eleves_list,
        name="voeux_eleves_list"
    ),
    path(
        "orientation/afficher-voeux/<int:eleve_id>/<int:orientation_id>/",
        views.voeu_eleve_detail,
        name="voeu_eleve_detail"
    ),
    path(
        "orientation/orientation-finale/",
        views.orientation_finale_page,
        name="orientation_finale_page"
    ),
    path(
        "orientation/rapport-orientation/",
        views.rapport_orientation_page,
        name="rapport_orientation_page"
    ),
    path(
        "orientation/decision-eleve/",
        views.decision_eleve_page,
        name="decision_eleve_page"
    ),
    path(
        "orientation/rapport-decision-finale/",
        views.rapport_decision_finale_page,
        name="rapport_decision_finale_page"
    ),
]