# Generated by Django 5.1.4 on 2026-01-07 08:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('a_specialite', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissancce', models.DateField()),
                ('Sexe', models.CharField(choices=[('M', 'musculin'), ('F', 'feminin')])),
                ('adrress', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(default='default.png', upload_to='eleve')),
                ('parent', models.CharField(max_length=120)),
                ('telephone_parent', models.CharField(blank=True, max_length=70)),
                ('email_parent', models.EmailField(blank=True, max_length=254, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='Ecole_admin.classe')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Matier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.classe')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Ecole_admin.niveau'),
        ),
        migrations.CreateModel(
            name='Proffeseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_conplet', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'musculin'), ('F', 'feminin')])),
                ('telephone', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=120)),
                ('diplome', models.FileField(blank=True, null=True, upload_to='diplomes/')),
                ('date_empauche', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Permanent', 'Permanent'), ('Vacataire', 'Vacataire'), ('Stagiaire', 'Stagiaire')], default='Permanent', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(related_name='professeurs', to='Ecole_admin.classe')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('matieres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='Ecole_admin.matier')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTempsSoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('soir', models.CharField(choices=[('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi')], max_length=15)),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploisoir', to='Ecole_admin.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.matier')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.proffeseur')),
            ],
            options={
                'verbose_name_plural': 'Emplois du temps de soir',
                'ordering': ['soir', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('jour', models.CharField(choices=[('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi')], max_length=15)),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='Ecole_admin.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.matier')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.proffeseur')),
            ],
            options={
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('justifiee', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='Ecole_admin.proffeseur')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('matier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Ecole_admin.matier')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Ecole_admin.proffeseur')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecole_admin.specialite'),
        ),
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_paiement', to='Ecole_admin.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Paiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('periode', models.CharField(max_length=50)),
                ('moyen', models.CharField(blank=True, max_length=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.eleve')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.typepaiement')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom_complet', models.CharField(default='Utilisateur inconue', max_length=20)),
                ('sexe', models.CharField(choices=[('M', 'musculin'), ('F', 'feminin')], default='M', max_length=1)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('Pays', models.CharField(default='Djibouti', max_length=50)),
                ('Ville', models.CharField(default='Djibouti', max_length=12)),
                ('Adresse', models.CharField(default='Adresse inconue', max_length=100)),
                ('num_tel', models.CharField(default='77******', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('secretaire', 'Secrétaire'), ('eleve', 'eleve'), ('proffesseur', 'proffesseur')], max_length=20, null=True)),
                ('is_eleve', models.BooleanField(default=False)),
                ('is_proffesseur', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='proffeseur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er trimestre'), (2, '2e trimestre'), (3, '3e trimestre')], default=1)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.matier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recus', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'ecole')},
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absence', 'Absence'), ('retard', 'Retard')], default='present', max_length=10)),
                ('date', models.DateField()),
                ('h_debut', models.TimeField(blank=True, null=True)),
                ('h_fin', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('justifiee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='Ecole_admin.eleve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'h_debut'],
                'unique_together': {('eleve', 'date', 'h_debut', 'h_fin')},
            },
        ),
    ]
