# Generated by Django 5.1.4 on 2026-01-07 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='eleve',
            name='identifiant',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='Sexe',
            field=models.CharField(choices=[('M', 'musculin'), ('F', 'feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='ecole',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole'),
        ),
    ]
