# Generated by Django 5.1.4 on 2026-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0002_eleve_date_inscription_eleve_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
