# Generated by Django 5.1.4 on 2026-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0003_eleve_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='identifiant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='eleve',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'identifiant'), name='uniq_eleve_identifiant_par_ecole_annee'),
        ),
    ]
