# Generated by Django 5.1.4 on 2026-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0004_alter_eleve_identifiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='actif',
            field=models.CharField(choices=[('R', 'Redouble'), ('F', 'Admie')], max_length=120),
        ),
    ]
