# Generated by Django 5.1.4 on 2026-01-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0005_alter_eleve_actif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='actif',
            new_name='status',
        ),
    ]
