# Generated by Django 5.1.4 on 2026-01-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0006_rename_actif_eleve_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(choices=[('DJF', 'DJF'), ('USD', 'USD'), ('EUR', 'EUR')], default='DJF', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_paiement', to='Ecole_admin.ecole')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='Ecole_admin.niveau')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='Ecole_admin.typepaiement')),
            ],
            options={
                'ordering': ['niveau', 'type_paiement'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'niveau', 'type_paiement'), name='uniq_tarif_par_ecole_annee_niveau_type')],
            },
        ),
    ]
