# Generated by Django 5.1.4 on 2026-01-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0007_tarifpaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='DJF', max_length=10)),
                ('paye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='Ecole_admin.eleve')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.niveau')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.typepaiement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'eleve', 'type_paiement'), name='uniq_frais_eleve_par_annee_type')],
            },
        ),
    ]
