# Generated by Django 5.1.4 on 2026-01-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0008_fraiseleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFraisEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='DJF', max_length=10)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Mobile money')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('frais_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Ecole_admin.fraiseleve')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
