# Generated by Django 5.1.4 on 2026-01-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0010_recucaisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneRecuCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='DJF', max_length=10)),
                ('frais_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_recu', to='Ecole_admin.fraiseleve')),
                ('recu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Ecole_admin.recucaisse')),
            ],
        ),
    ]
