# Generated by Django 5.1.4 on 2026-01-10 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0011_lignerecucaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='recucaisse',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recucaisse',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recucaisse',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recucaisse',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé'), ('annule', 'Annulé')], default='valide', max_length=10),
        ),
    ]
