# Generated by Django 5.1.4 on 2026-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0013_message_parent_message_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
