# Generated by Django 5.1.4 on 2026-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0015_remove_message_lu_remove_message_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='parent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_complet',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_tel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('secretaire', 'Secrétaire'), ('parent', 'Parent'), ('proffesseur', 'Professeur')], max_length=20, null=True),
        ),
    ]
