# Generated by Django 5.1.4 on 2026-01-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0016_alter_eleve_parent_alter_user_nom_complet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
