# Generated by Django 5.1.4 on 2026-01-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0017_delete_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='allow_reply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cible_classe',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cible_niveau',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cible_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cible_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='important',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_eleve',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_proffesseur',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proffeseur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_prof', to=settings.AUTH_USER_MODEL),
        ),
    ]
