# Generated by Django 5.1.4 on 2026-01-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0018_remove_message_allow_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('points', models.PositiveIntegerField(default=20)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('classes', models.ManyToManyField(related_name='devoirs', to='Ecole_admin.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.matier')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.niveau')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.proffeseur')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.AddField(
            model_name='note',
            name='devoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecole_admin.devoir'),
        ),
        migrations.CreateModel(
            name='PeriodeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('debut',),
                'unique_together': {('ecole', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='devoir',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.periodescolaire'),
        ),
        migrations.CreateModel(
            name='DispenseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(default='Disp', max_length=50)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.matier')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.periodescolaire')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('eleve', 'matiere', 'periode', 'annee_scolaire', 'ecole')},
            },
        ),
    ]
