# Generated by Django 5.1.4 on 2026-01-14 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0019_devoir_note_devoir_periodescolaire_devoir_periode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppreciationAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('abs_min', models.PositiveIntegerField(default=0)),
                ('abs_max', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('abs_min',),
                'unique_together': {('ecole', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='AppreciationAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('note_min', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('note_min',),
                'unique_together': {('ecole', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='AppreciationPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('note_min', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('note_min',),
                'unique_together': {('ecole', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ConfigMoyenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_de', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('moyenne_a', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('admis', 'Admis'), ('redouble', 'Redouble'), ('autorise', 'Autorisé(e)'), ('exclu', 'Exclu')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.niveau')),
            ],
            options={
                'ordering': ('niveau', 'moyenne_de'),
                'constraints': [models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'niveau', 'moyenne_de', 'moyenne_a', 'status'), name='uniq_cfg_moyenne_par_ecole_annee')],
            },
        ),
        migrations.CreateModel(
            name='ProlongationSaisieNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('actif', models.BooleanField(default=False)),
                ('prolonger_jours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.niveau')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.periodescolaire')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.proffeseur')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('ecole', 'annee_scolaire', 'professeur', 'niveau', 'periode')},
            },
        ),
    ]
