# Generated by Django 5.1.4 on 2026-01-14 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0020_appreciationabsence_appreciationannuelle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fonction', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('actif', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='CloturePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cloturee', models.BooleanField(default=False)),
                ('cloturee_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('periode_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.periodescolaire')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('ecole', 'annee_scolaire', 'periode_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='DecisionAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_abs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('R', 'Redouble'), ('F', 'Admis'), ('A', 'Autorisé(e)'), ('E', 'Exclu(e)')], max_length=2)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('max_abs',),
                'unique_together': {('ecole', 'annee_scolaire', 'max_abs', 'statut')},
            },
        ),
        migrations.CreateModel(
            name='DecisionPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ('decision',),
                'unique_together': {('ecole', 'annee_scolaire', 'decision')},
            },
        ),
    ]
