# Generated by Django 5.1.4 on 2026-01-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0021_signatureconfig_clotureperiode_decisionabsence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodescolaire',
            name='prolongation_jours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
