# Generated by Django 5.1.4 on 2026-01-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0022_periodescolaire_prolongation_jours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appreciationperiode',
            unique_together=set(),
        ),
    ]
