# Generated by Django 5.1.4 on 2026-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0023_alter_appreciationperiode_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(default='Djibouti', max_length=250),
        ),
    ]
