# Generated by Django 5.1.4 on 2026-01-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0024_eleve_lieu_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaisonConvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
        ),
    ]
