# Generated by Django 5.1.4 on 2026-01-21 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0025_raisonconvocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raisonconvocation',
            options={'ordering': ['libelle']},
        ),
        migrations.AlterField(
            model_name='raisonconvocation',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole'),
        ),
        migrations.AlterUniqueTogether(
            name='raisonconvocation',
            unique_together={('ecole', 'libelle')},
        ),
        migrations.CreateModel(
            name='ConvocationParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('date_convocation', models.DateField(default=django.utils.timezone.localdate)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocations_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.eleve')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.niveau')),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocations_recues', to=settings.AUTH_USER_MODEL)),
                ('raison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ecole_admin.raisonconvocation')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypeViolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ViolenceEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateField(default=django.utils.timezone.localdate)),
                ('lieu', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('grave', 'Grave')], default='moyenne', max_length=10)),
                ('action_pris', models.CharField(blank=True, max_length=255)),
                ('parent_informe', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violences_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violences', to='Ecole_admin.eleve')),
                ('type_violence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violences', to='Ecole_admin.typeviolence')),
            ],
            options={
                'ordering': ['-date_incident', '-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='typeviolence',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'nom'), name='uniq_type_violence_par_ecole_annee_nom'),
        ),
    ]
