# Generated by Django 5.1.4 on 2026-01-21 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0026_alter_raisonconvocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violenceeleve',
            name='type_violence',
        ),
        migrations.RemoveField(
            model_name='violenceeleve',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='violenceeleve',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='violenceeleve',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='violenceeleve',
            name='eleve',
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme_agression', models.TextField()),
                ('cause_violence', models.TextField()),
                ('dommage_corporel', models.TextField()),
                ('moyens_resolution', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agresseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violences_agresseur', to='Ecole_admin.eleve')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('victime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violences_victime', to='Ecole_admin.eleve')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TypeViolence',
        ),
        migrations.DeleteModel(
            name='ViolenceEleve',
        ),
    ]
