# Generated by Django 5.1.4 on 2026-01-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0027_remove_violenceeleve_type_violence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violence',
            name='agresseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violences_agresseur', to='Ecole_admin.eleve'),
        ),
        migrations.AlterField(
            model_name='violence',
            name='victime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violences_victime', to='Ecole_admin.eleve'),
        ),
    ]
