# Generated by Django 5.1.4 on 2026-01-21 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0028_alter_violence_agresseur_alter_violence_victime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to=settings.AUTH_USER_MODEL),
        ),
    ]
