# Generated by Django 5.1.4 on 2026-01-22 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0029_alter_eleve_parent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degradation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degradation_commise', models.TextField()),
                ('decision_prise', models.CharField(choices=[('avertissement', 'Avertissement'), ('convocation_parent', 'Convocation des parents'), ('reparation', 'Réparation / Remboursement'), ('travail_interet', 'Travail d’intérêt général'), ('exclusion_temp', 'Exclusion temporaire'), ('autre', 'Autre (personnalisée)')], max_length=40)),
                ('decision_autre', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='degradations', to='Ecole_admin.eleve')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
