# Generated by Django 5.1.4 on 2026-01-24 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0030_degradation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('matricule', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('fonction', models.CharField(choices=[('gardien', 'Gardien'), ('surveillant', 'Surveillant'), ('entretien', 'Agent d’entretien'), ('concierge', 'Concierge'), ('chauffeur', 'Chauffeur'), ('cuisinier', 'Cuisinier'), ('cantine', 'Cantinier / Cantine'), ('administratif', 'Agent administratif'), ('comptable', 'Comptable'), ('bibliothecaire', 'Bibliothécaire'), ('it', 'Technicien informatique'), ('electricien', 'Électricien'), ('plombier', 'Plombier'), ('autre', 'Autre')], max_length=30)),
                ('autre_fonction', models.CharField(blank=True, default='', max_length=120)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('bureau', models.CharField(blank=True, default='', max_length=120)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('working_hours', models.PositiveIntegerField(default=8)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'matricule'), name='uniq_employe_matricule_par_ecole')],
            },
        ),
    ]
