# Generated by Django 5.1.4 on 2026-01-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0031_employe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employe',
            name='uniq_employe_matricule_par_ecole',
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('ecole', 'matricule'), name='unique_matricule_par_ecole'),
        ),
    ]
