# Generated by Django 5.1.4 on 2026-01-24 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0032_remove_employe_uniq_employe_matricule_par_ecole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesseurAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absence', 'Absence'), ('retard', 'Retard')], default='absence', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('h_debut', models.TimeField(blank=True, null=True)),
                ('h_fin', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('justifiee', models.BooleanField(default=False)),
                ('piece', models.FileField(blank=True, null=True, upload_to='absences_prof/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='Ecole_admin.proffeseur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_prof_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'professeur__nom_conplet'],
            },
        ),
        migrations.DeleteModel(
            name='AbsenceProfesseur',
        ),
        migrations.AddConstraint(
            model_name='professeurabsence',
            constraint=models.UniqueConstraint(fields=('professeur', 'date', 'h_debut', 'h_fin', 'annee_scolaire', 'ecole'), name='uniq_absence_prof_par_date_heure_ecole_annee'),
        ),
    ]
