# Generated by Django 5.1.4 on 2026-01-25 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0033_professeurabsence_delete_absenceprofesseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absence', 'Absence'), ('retard', 'Retard')], default='absence', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('h_debut', models.TimeField(blank=True, null=True)),
                ('h_fin', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('justifiee', models.BooleanField(default=False)),
                ('piece', models.FileField(blank=True, null=True, upload_to='absences_employes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='Ecole_admin.employe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_employe_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employe__nom_complet'],
                'constraints': [models.UniqueConstraint(fields=('employe', 'date', 'h_debut', 'h_fin', 'annee_scolaire', 'ecole'), name='uniq_absence_employe_par_date_heure_ecole_annee')],
            },
        ),
    ]
