# Generated by Django 5.1.4 on 2026-01-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0035_batiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('etage', models.SmallIntegerField(default=0)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salles', to='Ecole_admin.batiment')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ['nom', 'id'],
                'unique_together': {('ecole', 'batiment', 'nom')},
            },
        ),
    ]
