# Generated by Django 5.1.4 on 2026-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0036_salle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salle',
            options={'ordering': ['batiment__nom', 'nom', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('ecole', 'batiment', 'nom', 'etage')},
        ),
        migrations.AlterField(
            model_name='salle',
            name='etage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='salle',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='capacite',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='code',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='created_at',
        ),
    ]
