# Generated by Django 5.1.4 on 2026-01-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0037_alter_salle_options_alter_salle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='Ecole_admin.salle'),
        ),
    ]
