# Generated by Django 5.1.4 on 2026-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0038_alter_emploidutemps_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=2),
        ),
    ]
