# Generated by Django 5.1.4 on 2026-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0039_ecole_langue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='status',
            field=models.CharField(choices=[('ADMIS', 'Admis'), ('REDOUBLE', 'Redouble')], max_length=120),
        ),
    ]
