# Generated by Django 5.1.4 on 2026-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0040_alter_eleve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('ecole', 'nom'), name='uniq_niveau_ecole_nom'),
        ),
    ]
