# Generated by Django 5.1.4 on 2026-03-03 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0041_alter_niveau_nom_niveau_uniq_niveau_ecole_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='autre_fonction',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Autre fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='bureau',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Bureau'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='Ecole_admin.ecole', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.CharField(choices=[('gardien', 'Gardien'), ('surveillant', 'Surveillant'), ('entretien', 'Agent d’entretien'), ('concierge', 'Concierge'), ('chauffeur', 'Chauffeur'), ('cuisinier', 'Cuisinier'), ('cantine', 'Cantinier / Cantine'), ('administratif', 'Agent administratif'), ('comptable', 'Comptable'), ('bibliothecaire', 'Bibliothécaire'), ('it', 'Technicien informatique'), ('electricien', 'Électricien'), ('plombier', 'Plombier'), ('autre', 'Autre')], max_length=30, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom_complet',
            field=models.CharField(max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='working_hours',
            field=models.PositiveIntegerField(default=8, verbose_name='Heures de travail'),
        ),
    ]
