# Generated by Django 5.1.4 on 2026-03-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0042_alter_employe_options_alter_employe_autre_fonction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Pays',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ville',
            field=models.CharField(default='', max_length=52),
        ),
    ]
