# Generated by Django 5.1.4 on 2026-03-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0043_alter_user_adresse_alter_user_pays_alter_user_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('ADMIS', 'Admis'), ('REDOUBLE', 'Redouble'), ('AUTORISE', 'Autorisé(e)'), ('ORIENTE', 'Orienté(e)'), ('DIPLOME', 'Diplômé(e)'), ('EXCLU', 'Exclu(e)')], default='EN_COURS', max_length=120),
        ),
        migrations.CreateModel(
            name='PromotionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_annuelle', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_absences', models.PositiveIntegerField(default=0)),
                ('total_retards', models.PositiveIntegerField(default=0)),
                ('decision_proposee', models.CharField(choices=[('attente', 'En attente'), ('admis', 'Admis'), ('redouble', 'Redouble'), ('autorise', 'Autorisé(e)'), ('oriente', 'Orienté(e)'), ('diplome', 'Diplômé(e)'), ('exclu', 'Exclu(e)')], default='attente', max_length=20)),
                ('decision_finale', models.CharField(choices=[('attente', 'En attente'), ('admis', 'Admis'), ('redouble', 'Redouble'), ('autorise', 'Autorisé(e)'), ('oriente', 'Orienté(e)'), ('diplome', 'Diplômé(e)'), ('exclu', 'Exclu(e)')], default='attente', max_length=20)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('evalue', 'Évalué'), ('valide', 'Validé'), ('execute', 'Exécuté')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('est_diplome', models.BooleanField(default=False)),
                ('est_traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_eleves', to='Ecole_admin.anneescolaire')),
                ('classe_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_classe_actuelle', to='Ecole_admin.classe')),
                ('decision_personnalisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_personnalisees', to='Ecole_admin.decisionpromotion')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_eleves', to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='Ecole_admin.eleve')),
                ('evalue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_evaluees', to=settings.AUTH_USER_MODEL)),
                ('execute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_executees', to=settings.AUTH_USER_MODEL)),
                ('niveau_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_niveau_actuel', to='Ecole_admin.niveau')),
                ('prochaine_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_classe_cible', to='Ecole_admin.classe')),
                ('prochaine_niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_niveau_cible', to='Ecole_admin.niveau')),
                ('prochaine_specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_specialite_cible', to='Ecole_admin.specialite')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classe_actuelle__nom', 'eleve__nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueChangementClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('attente', 'En attente'), ('admis', 'Admis'), ('redouble', 'Redouble'), ('autorise', 'Autorisé(e)'), ('oriente', 'Orienté(e)'), ('diplome', 'Diplômé(e)'), ('exclu', 'Exclu(e)')], default='attente', max_length=20)),
                ('source', models.CharField(choices=[('promotion', 'Promotion'), ('orientation', 'Orientation'), ('manuel', 'Manuel')], default='manuel', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ancienne_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_classes_changement', to='Ecole_admin.classe')),
                ('ancienne_niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciens_niveaux_changement', to='Ecole_admin.niveau')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_changement_classe', to='Ecole_admin.anneescolaire')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_classe_crees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_changement_classe', to='Ecole_admin.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_changement_classe', to='Ecole_admin.eleve')),
                ('nouvelle_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouvelles_classes_changement', to='Ecole_admin.classe')),
                ('nouvelle_niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouveaux_niveaux_changement', to='Ecole_admin.niveau')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='Ecole_admin.promotioneleve')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promotioneleve',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'eleve'), name='uniq_promotion_eleve_par_ecole_annee'),
        ),
    ]
