# Generated by Django 5.1.4 on 2026-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0044_alter_eleve_status_promotioneleve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau__ordre', 'ordre', 'nom']},
        ),
        migrations.AddField(
            model_name='classe',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text='Ordre de la classe dans le niveau (ex: 1, 2, 3...)'),
        ),
    ]
