# Generated by Django 5.1.4 on 2026-04-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0045_alter_classe_options_classe_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeOrientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(blank=True, max_length=120)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
            ],
            options={
                'ordering': ['ordre', 'code'],
                'unique_together': {('ecole', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrientationScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientations_scolaires', to='Ecole_admin.niveau')),
                ('programmes', models.ManyToManyField(related_name='orientations_scolaires', to='Ecole_admin.programmeorientation')),
            ],
            options={
                'ordering': ['niveau__ordre', 'niveau__nom'],
                'unique_together': {('ecole', 'annee_scolaire', 'niveau')},
            },
        ),
    ]
