# Generated by Django 5.1.4 on 2026-04-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0046_programmeorientation_orientationscolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientationscolaire',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='orientations_scolaires', to='Ecole_admin.programmeorientation'),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='libelle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
