# Generated by Django 5.1.4 on 2026-04-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0047_alter_orientationscolaire_programmes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orientationscolaire',
            options={'ordering': ['niveau__ordre', 'niveau__nom'], 'verbose_name': 'Orientation scolaire', 'verbose_name_plural': 'Orientations scolaires'},
        ),
        migrations.AlterModelOptions(
            name='programmeorientation',
            options={'ordering': ['ordre', 'code'], 'verbose_name': "Programme d'orientation", 'verbose_name_plural': "Programmes d'orientation"},
        ),
        migrations.AlterUniqueTogether(
            name='orientationscolaire',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programmeorientation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecole_admin.ecole', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientations_scolaires', to='Ecole_admin.niveau', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='orientationscolaire',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='orientations_scolaires', to='Ecole_admin.programmeorientation', verbose_name='Programmes'),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='code',
            field=models.CharField(help_text='Exemple : ES, S, L, GFM, OGRH, IAG', max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_orientation', to='Ecole_admin.ecole', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='libelle',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='programmeorientation',
            name='ordre',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordre'),
        ),
        migrations.AddConstraint(
            model_name='orientationscolaire',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'niveau'), name='uniq_orientation_scolaire_ecole_annee_niveau'),
        ),
        migrations.AddConstraint(
            model_name='programmeorientation',
            constraint=models.UniqueConstraint(fields=('ecole', 'code'), name='uniq_programme_orientation_ecole_code'),
        ),
    ]
