# Generated by Django 5.1.4 on 2026-04-05 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0048_alter_orientationscolaire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoeuOrientationEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voeux_orientation_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux_orientation', to='Ecole_admin.eleve', verbose_name='Élève')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux_eleves', to='Ecole_admin.orientationscolaire', verbose_name='Orientation scolaire')),
            ],
            options={
                'verbose_name': "Vœu d'orientation élève",
                'verbose_name_plural': "Vœux d'orientation élèves",
                'ordering': ['eleve__nom'],
            },
        ),
        migrations.CreateModel(
            name='VoeuOrientationChoix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_voeux', to='Ecole_admin.programmeorientation', verbose_name='Programme')),
                ('voeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='Ecole_admin.voeuorientationeleve', verbose_name='Vœu')),
            ],
            options={
                'verbose_name': 'Choix de vœu',
                'verbose_name_plural': 'Choix de vœux',
                'ordering': ['programme__ordre', 'programme__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='voeuorientationeleve',
            constraint=models.UniqueConstraint(fields=('eleve', 'orientation'), name='uniq_voeu_orientation_par_eleve_orientation'),
        ),
        migrations.AddConstraint(
            model_name='voeuorientationchoix',
            constraint=models.UniqueConstraint(fields=('voeu', 'programme'), name='uniq_choix_par_voeu_programme'),
        ),
    ]
