# Generated by Django 5.1.4 on 2026-04-05 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0049_voeuorientationeleve_voeuorientationchoix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationFinaleEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.CharField(blank=True, default='', max_length=255, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientations_finales_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientations_finales', to='Ecole_admin.eleve', verbose_name='Élève')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientations_finales_eleves', to='Ecole_admin.orientationscolaire', verbose_name='Orientation scolaire')),
                ('programme_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientations_finales', to='Ecole_admin.programmeorientation', verbose_name='Programme final')),
            ],
            options={
                'verbose_name': 'Orientation finale élève',
                'verbose_name_plural': 'Orientations finales élèves',
                'ordering': ['eleve__nom'],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'orientation'), name='uniq_orientation_finale_par_eleve_orientation')],
            },
        ),
    ]
