# Generated by Django 5.1.4 on 2026-04-05 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole_admin', '0050_orientationfinaleeleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionFinaleEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Moyenne annuelle')),
                ('remarque', models.CharField(blank=True, default='', max_length=255, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_finales_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_eleves', to='Ecole_admin.decisionpromotion', verbose_name='Décision')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_finales', to='Ecole_admin.eleve', verbose_name='Élève')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_finales_eleves', to='Ecole_admin.orientationscolaire', verbose_name='Orientation scolaire')),
                ('orientation_finale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_administratives', to='Ecole_admin.orientationfinaleeleve', verbose_name='Orientation finale')),
            ],
            options={
                'verbose_name': 'Décision finale élève',
                'verbose_name_plural': 'Décisions finales élèves',
                'ordering': ['eleve__nom'],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'orientation'), name='uniq_decision_finale_par_eleve_orientation')],
            },
        ),
    ]
